WIP: Add helper function for generating multiple prekeys
freedomofpress/signal-protocol pull request #14
Opened 2020-12-03 04:55 UTC by pierwill

Closes #7.

I've chosen a default number of prekeys to generate (100). This (possible) convenience means the user must specify a `None` parameter for `n`. (When she does not, there's a pretty confusing error message, as well, so it might be best to go with a get_n_prekeys pattern as suggested originally.)

2020-12-04 22:01 UTC, redshiftzero requested changes
nice work! just one comment inline to look at

2020-12-04 22:34 UTC, pierwill commented on src/state.rs
> +        let prekey = PreKeyRecord::new(id, keypair);
Ah! I had wondered about this at some point. I'm on it.

2020-12-04 22:55 UTC, pierwill commented on src/state.rs
> +        let prekey = PreKeyRecord::new(id, keypair);
Do we need to worry about PreKeyId collisions? Do we know (or need to know) globally which IDs have been used?

2020-12-04 23:12 UTC, redshiftzero commented on src/state.rs
> +        let prekey = PreKeyRecord::new(id, keypair);
good question, my thinking is that the expectation should be that the PreKeyRecords returned from this function all have unique IDs (i.e. there are no collisions). 

Regarding used prekey IDs more generally, the object in these bindings that has that information is the `InMemSignalProtocolStore` (via the `InMemPreKeyStore` in the [upstream crate](https://github.com/signalapp/libsignal-client/blob/master/rust/protocol/src/storage/inmem.rs#L119-L128)). Right now as you can see from the linked logic, the prekey store will just transparently replace records with duplicated key IDs (imho it should probably be an error), but until that changes it's the responsibility of clients to (separately from this function) keep track of what their last used PreKeyID is so they don't accidentally overwrite a stored PreKeyRecord. 

let me know what you think!

2020-12-04 23:33 UTC, pierwill commented on src/state.rs
> +        let prekey = PreKeyRecord::new(id, keypair);
Hm. A check for each ID into the InMemSignalProtocolStore (if it exists?) when generated is probably the most foolproof and robust way at the moment, no? :thinking:

2020-12-04 23:34 UTC, pierwill commented on src/state.rs
> +        let keypair = KeyPair::generate();
When I play with this on the Python end, it still looks suspiciously like we're not getting a new KeyPair:

```python
In [2]: x = 1

In [3]: while x < 50:
   ...:     print(manykeys[x].id())
   ...:     print(manykeys[x].key_pair())
   ...:     x += 1
   ...: 
2
<KeyPair object at 0x733690406c38>
3
<KeyPair object at 0x733690406c38>
4
<KeyPair object at 0x733690406c38>
5
<KeyPair object at 0x733690406c38>
6
<KeyPair object at 0x733690406c38>
7
```

2020-12-04 23:36 UTC, pierwill commented on src/state.rs
> +        let prekey = PreKeyRecord::new(id, keypair);
Using `InMemSignalProtocolStore::get_pre_key`?

2020-12-04 23:50 UTC, pierwill commented on src/state.rs
> +        let keypair = KeyPair::generate();
*Howeeever*, the test I wrote just passed.

```python
prekeyrecords = state.generate_n_prekeys(256, pre_key_id)
    assert len(prekeyrecords) == 256
    assert prekeyrecords[12].id() != prekeyrecords[13].id()
    assert prekeyrecords[14].key_pair() != prekeyrecords[15].key_pair()
```

2020-12-05 00:27 UTC, pierwill commented on src/state.rs
> +        let prekey = PreKeyRecord::new(id, keypair);
Although, reading your comments again, doing a collision check in the body of `state::generate_n_keys` might not be necessary given then implicit contract.

2020-12-07 23:08 UTC, redshiftzero approved these changes
looks good, thanks!

2020-12-07 23:08 UTC, merged